---
title: "Preparing Data For Analysis"
author: "Nicole Hill"
date: "10/27/2020"
output: html_document
---

# Packages & Data

```{r , message=FALSE}
library( stringr )
library( dplyr )
library( pander )
library( tidyr)
```

```{r}
URL <- "https://raw.githubusercontent.com/R-Class/cpp-528-fall-2020-group-02/main/data/raw/ltdb-data-dictionary.csv?token=AOIC6SHE3Q3BDT3CMZQE75C7UGZSK"
data <- read.csv( URL, stringsAsFactors=F )
head( data ) %>% pander()
```

# Part 2: Build a Variable Filter

## ONE: Filter variables by theme or group

```{r}
# CREATE FUNCTION THAT WILL FILTER CATEGORY VARIABLE BY KEYWORD AND RETURN A DATAFRAME
filter_by_group <- function( keyword )
  {
      output_df <- 
        data %>%
        filter( category %in% keyword )
      
      return( output_df )
}

# TEST FUNCTION
filter_by_group( "age" ) %>% pander()
```

## TWO: Searches variable descriptions for a specific string and returns any variables that match

```{r}
# CREATE FUNCTION THAT WILL FILTER DEFINITION VARIABLE BY KEYWORD AND RETURN A DATAFRAME
search_description <- function( keyword )
  {
      output_df <- 
        data %>%
        filter( str_detect( definition , keyword ) )

      return( output_df )
}

# TEST FUNCTION
search_description( "poverty" ) %>% pander()
```

## THREE: Filter variables by time periods

```{r}
# CREATE FUNCTION THAT WILL FILTER BY YEAR AND RETURN A DATAFRAME
filter_by_year <- function( year ) 
  {
      df <-  data %>% gather( key = "year", value = "variable_name" , -root , -root2 , -category , -definition )
  
        output_df <- 
        df %>%
        filter( str_detect( year , c( "1970" , "1980" , "1990" , "2000" , "2010" ) ) )
        
        
        return( output_df )
}

# TEST FUNCTION
filter_by_year( "2010") %>% pander()
```


